/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PersonBUS;
import DTO.PersonDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ReaderDetail extends javax.swing.JPanel {
    private PersonDTO personDTO;
    private ReaderGUI parentGUI;
    /**
     * Creates new form ReaderDetail
     */
    public ReaderDetail(ReaderGUI parentGUI) {
        initComponents();
        this.parentGUI = parentGUI;
        showReaderDetail();
    }
    
    public void showReaderDetail(){
        if (personDTO == null){
            panelBorder1.setVisible(false);
        }else{    
            panelBorder1.setVisible(true);
            loadValueReader(personDTO);
        }
    }
    
    public void setPersonDTO(PersonDTO personDTO){
        this.personDTO = personDTO;
    }
    
    public void setValue(){
        if (personDTO.getRoleID().getId().equals("GV")){
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            startYearLabel.setVisible(false);
            endYearLabel.setVisible(false);
        } else {
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            startYearLabel.setVisible(true);
            endYearLabel.setVisible(true);
        }
    }
    
    public void loadValueReader(PersonDTO personDTO){
        readerIdLabel.setText(personDTO.getId());
        readerRoleLabel.setText(personDTO.getRoleID().getId().equals("SV") ? "Sinh viên" : "Giảng viên");
        readerNameTextField.setText(personDTO.getName());
        readerTelTextField.setText(personDTO.getTel());
        
        readerAddressTextField.setText(personDTO.getAddress());
        String temp = personDTO.getSchoolYear();
        if (temp != null) {
            String[] element = temp.split("-");
            startYearLabel.setText(element[0]);
            endYearLabel.setText(element[1]);
        }
        setValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new MyDesign.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        readerNameTextField = new MyDesign.MyTextField_Basic();
        jLabel4 = new javax.swing.JLabel();
        readerTelTextField = new MyDesign.MyTextField_Basic();
        jLabel5 = new javax.swing.JLabel();
        readerAddressTextField = new MyDesign.MyTextField_Basic();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        startYearLabel = new javax.swing.JLabel();
        endYearLabel = new javax.swing.JLabel();
        readerIdLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        readerRoleLabel = new javax.swing.JLabel();
        editBookButton = new MyDesign.MyButton();
        deleteBookButton1 = new MyDesign.MyButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN ĐỘC GIẢ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã độc giả");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên độc giả");

        readerNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        readerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerNameTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Số điện thoại");

        readerTelTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Địa chỉ");

        readerAddressTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Năm học bắt đầu");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Năm học kết thúc");

        startYearLabel.setText("2021");

        endYearLabel.setText("2026");

        readerIdLabel.setText("2021");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Vai trò");

        readerRoleLabel.setText("Sinh viên hay Giảng viên");

        editBookButton.setBackground(new java.awt.Color(22, 113, 221));
        editBookButton.setForeground(new java.awt.Color(255, 255, 255));
        editBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/icon/action-refresh-white.png"))); // NOI18N
        editBookButton.setColor(new java.awt.Color(22, 113, 221));
        editBookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editBookButton.setLabel("Cập nhật ");
        editBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookButtonActionPerformed(evt);
            }
        });

        deleteBookButton1.setForeground(new java.awt.Color(248, 67, 67));
        deleteBookButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/icon/action-delete-white.png"))); // NOI18N
        deleteBookButton1.setColor(new java.awt.Color(255, 241, 241));
        deleteBookButton1.setColorOver(new java.awt.Color(255, 241, 241));
        deleteBookButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBookButton1.setLabel("Xoá ");
        deleteBookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookButton1ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/img/icon/info-history.png"))); // NOI18N
        jLabel9.setText("Lịch sử mượn sách");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(readerIdLabel))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(readerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(readerTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(readerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(endYearLabel))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startYearLabel))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(readerRoleLabel))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1))
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(editBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBookButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(readerIdLabel))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(readerRoleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(readerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(readerTelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(startYearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(endYearLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBookButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookButtonActionPerformed
        
        if (personDTO == null) {
            JOptionPane.showMessageDialog(this, "Không có thông tin độc giả để cập nhật!");
            return;
        }
        String newName = readerNameTextField.getText();
        String newTel = readerTelTextField.getText();
        String newAddress = readerAddressTextField.getText();

        if (newName.isEmpty() || newTel.isEmpty() || newAddress.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }
        if (!newName.matches("^[\\p{L}\\s]+$")){
            JOptionPane.showMessageDialog(this, "Tên không hợp lệ!");
            return;
        }
        if (!newTel.matches("^\\d{10}$")){
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ!");
            return;
        }

        personDTO.setName(newName);
        personDTO.setTel(newTel);
        personDTO.setAddress(newAddress);

        boolean isUpdated = new PersonBUS().updatePerson(personDTO); // Gọi BUS để cập nhật
        if (isUpdated) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin độc giả thành công!");
            this.parentGUI.refreshReaderTable();
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thất bại!");
        }    
    }//GEN-LAST:event_editBookButtonActionPerformed

    private void deleteBookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookButton1ActionPerformed
        // TODO add your handling code here:
        if (personDTO == null) {
        JOptionPane.showMessageDialog(this, "Không có thông tin độc giả để xóa!");
        return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn xóa độc giả này?", 
            "Xác nhận", JOptionPane.YES_NO_OPTION);
        boolean isDeleted = new PersonBUS().deletePerson(personDTO.getId());
        if (confirm == JOptionPane.YES_OPTION) {
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Xóa độc giả thành công!");
                personDTO = null; // Xóa thông tin đang hiển thị
                showReaderDetail();
                this.parentGUI.refreshReaderTable();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa độc giả thất bại!");
            }
        }
    }//GEN-LAST:event_deleteBookButton1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        ReaderHistoryDialog whid=new ReaderHistoryDialog(new javax.swing.JFrame(), true, this.personDTO.getId());
        whid.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void readerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readerNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyDesign.MyButton deleteBookButton1;
    private MyDesign.MyButton editBookButton;
    private javax.swing.JLabel endYearLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private MyDesign.PanelBorder panelBorder1;
    private MyDesign.MyTextField_Basic readerAddressTextField;
    private javax.swing.JLabel readerIdLabel;
    private MyDesign.MyTextField_Basic readerNameTextField;
    private javax.swing.JLabel readerRoleLabel;
    private MyDesign.MyTextField_Basic readerTelTextField;
    private javax.swing.JLabel startYearLabel;
    // End of variables declaration//GEN-END:variables
}
